# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: main
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    target-branch: main
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"